// User Action Types
export const USER_ACTION_TYPES = {
  // Get User Profile
  GET_USER_PROFILE_REQUEST: "GET_USER_PROFILE_REQUEST",
  GET_USER_PROFILE_SUCCESS: "GET_USER_PROFILE_SUCCESS",
  GET_USER_PROFILE_FAILURE: "GET_USER_PROFILE_FAILURE",

  // Get User Storage
  GET_USER_STORAGE_REQUEST: "GET_USER_STORAGE_REQUEST",
  GET_USER_STORAGE_SUCCESS: "GET_USER_STORAGE_SUCCESS",
  GET_USER_STORAGE_FAILURE: "GET_USER_STORAGE_FAILURE",

  // Update Profile
  UPDATE_PROFILE_REQUEST: "UPDATE_PROFILE_REQUEST",
  UPDATE_PROFILE_SUCCESS: "UPDATE_PROFILE_SUCCESS",
  UPDATE_PROFILE_FAILURE: "UPDATE_PROFILE_FAILURE",

  // Upload Avatar
  UPLOAD_AVATAR_REQUEST: "UPLOAD_AVATAR_REQUEST",
  UPLOAD_AVATAR_SUCCESS: "UPLOAD_AVATAR_SUCCESS",
  UPLOAD_AVATAR_FAILURE: "UPLOAD_AVATAR_FAILURE",
};