// Plan Action Types
export const PLAN_ACTION_TYPES = {
  // Get All Plans
  GET_ALL_PLANS_REQUEST: "GET_ALL_PLANS_REQUEST",
  GET_ALL_PLANS_SUCCESS: "GET_ALL_PLANS_SUCCESS",
  GET_ALL_PLANS_FAILURE: "GET_ALL_PLANS_FAILURE",

  // Subscribe Plan
  SUBSCRIBE_PLAN_REQUEST: "SUBSCRIBE_PLAN_REQUEST",
  SUBSCRIBE_PLAN_SUCCESS: "SUBSCRIBE_PLAN_SUCCESS",
  SUBSCRIBE_PLAN_FAILURE: "SUBSCRIBE_PLAN_FAILURE",

  // Cancel Subscription
  CANCEL_SUBSCRIPTION_REQUEST: "CANCEL_SUBSCRIPTION_REQUEST",
  CANCEL_SUBSCRIPTION_SUCCESS: "CANCEL_SUBSCRIPTION_SUCCESS",
  CANCEL_SUBSCRIPTION_FAILURE: "CANCEL_SUBSCRIPTION_FAILURE",

  // Get Current Plan
  GET_CURRENT_PLAN_REQUEST: "GET_CURRENT_PLAN_REQUEST",
  GET_CURRENT_PLAN_SUCCESS: "GET_CURRENT_PLAN_SUCCESS",
  GET_CURRENT_PLAN_FAILURE: "GET_CURRENT_PLAN_FAILURE",
};
