// Auth Action Types
export const AUTH_ACTION_TYPES = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS', 
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  
  REGISTER_REQUEST: 'REGISTER_REQUEST',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILURE: 'REGISTER_FAILURE',
  
  GOOGLE_LOGIN_REQUEST: 'GOOGLE_LOGIN_REQUEST',
  GOOGLE_LOGIN_SUCCESS: 'GOOGLE_LOGIN_SUCCESS',
  GOOGLE_LOGIN_FAILURE: 'GOOGLE_LOGIN_FAILURE',
  
  LOGOUT: 'LOGOUT',
  
  SET_AUTH_TOKEN: 'SET_AUTH_TOKEN',
  CLEAR_AUTH_TOKEN: 'CLEAR_AUTH_TOKEN',
  
  SET_USER: 'SET_USER',
  CLEAR_USER: 'CLEAR_USER'
};