export const ADMIN_DASHBOARD_ACTION_TYPES = {
  GET_DASHBOARD_DATA_REQUEST: 'GET_DASHBOARD_DATA_REQUEST',
  GET_DASHBOARD_DATA_SUCCESS: 'GET_DASHBOARD_DATA_SUCCESS', 
  GET_DASHBOARD_DATA_FAILURE: 'GET_DASHBOARD_DATA_FAILURE',
  CLEAR_DASHBOARD_DATA: 'CLEAR_DASHBOARD_DATA'
};