// Document Action Types
export const DOCUMENT_ACTION_TYPES = {
  /* DOCUMENT */
  TRASH_REQUEST: "TRASH_REQUEST",
  TRASH_SUCCESS: "TRASH_SUCCESS",
  TRASH_FAILURE: "TRASH_FAILURE",

  RESTORE_REQUEST: "RESTORE_REQUEST",
  RESTORE_SUCCESS: "RESTORE_SUCCESS",
  RESTORE_FAILURE: "RESTORE_FAILURE",

  GET_FOLDER_USERID_TYPE_REQUEST: "GET_FOLDER_USERID_TYPE_REQUEST",
  GET_FOLDER_USERID_TYPE_SUCCESS: "GET_FOLDER_USERID_TYPE_SUCCESS",
  GET_FOLDER_USERID_TYPE_FAILURE: "GET_FOLDER_USERID_TYPE_FAILURE",

  GET_FOLDER_USERID_REQUEST: "GET_FOLDER_USERID_REQUEST",
  GET_FOLDER_USERID_SUCCESS: "GET_FOLDER_USERID_SUCCESS",
  GET_FOLDER_USERID_FAILURE: "GET_FOLDER_USERID_FAILURE",

  GET_SAVED_USERID_REQUEST: "GET_SAVED_USERID_REQUEST",
  GET_SAVED_USERID_SUCCESS: "GET_SAVED_USERID_SUCCESS",
  GET_SAVED_USERID_FAILURE: "GET_SAVED_USERID_FAILURE",

  GET_ALL_USERID_REQUEST: "GET_ALL_USERID_REQUEST",
  GET_ALL_USERID_SUCCESS: "GET_ALL_USERID_SUCCESS",
  GET_ALL_USERID_FAILURE: "GET_ALL_USERID_FAILURE",

  GET_TRASH_USERID_REQUEST: "GET_TRASH_USERID_REQUEST",
  GET_TRASH_USERID_SUCCESS: "GET_TRASH_USERID_SUCCESS",
  GET_TRASH_USERID_FAILURE: "GET_TRASH_USERID_FAILURE",

  DELETE_PERMANENT_REQUEST: "DELETE_PERMANENT_REQUEST",
  DELETE_PERMANENT_SUCCESS: "DELETE_PERMANENT_SUCCESS",
  DELETE_PERMANENT_FAILURE: "DELETE_PERMANENT_FAILURE",

  /* DOCUMENT CLASSIFICATION */

  UPLOAD_FILE_REQUEST: "UPLOAD_FILE_REQUEST",
  UPLOAD_FILE_SUCCESS: "UPLOAD_FILE_SUCCESS",
  UPLOAD_FILE_FAILURE: "UPLOAD_FILE_FAILURE",

  PROCESS_URL_REQUEST: "PROCESS_URL_REQUEST",
  PROCESS_URL_SUCCESS: "PROCESS_URL_SUCCESS",
  PROCESS_URL_FAILURE: "PROCESS_URL_FAILURE",

  CLEANUP_TEMP_REQUEST: "CLEANUP_TEMP_REQUEST",
  CLEANUP_TEMP_SUCCESS: "CLEANUP_TEMP_SUCCESS",
  CLEANUP_TEMP_FAILURE: "CLEANUP_TEMP_FAILURE",

  /* DOCUMENT METADATA */

  EXTRACT_SAVE_REQUEST: "EXTRACT_SAVE_REQUEST",
  EXTRACT_SAVE_SUCCESS: "EXTRACT_SAVE_SUCCESS",
  EXTRACT_SAVE_FAILURE: "EXTRACT_SAVE_FAILURE",

  EXTRACT_METADATA_REQUEST: "EXTRACT_METADATA_REQUEST",
  EXTRACT_METADATA_SUCCESS: "EXTRACT_METADATA_SUCCESS",
  EXTRACT_METADATA_FAILURE: "EXTRACT_METADATA_FAILURE",

  GET_METADATA_DOCID_REQUEST: "GET_METADATA_DOCID_REQUEST",
  GET_METADATA_DOCID_SUCCESS: "GET_METADATA_DOCID_SUCCESS",
  GET_METADATA_DOCID_FAILURE: "GET_METADATA_DOCID_FAILURE",
};
