export const CITATION_ACTION_TYPES = {
  GENERATE_REQUEST: "GENERATE_REQUEST",
  GENERATE_SUCCESS: "GENERATE_SUCCESS",
  GENERATE_FAILURE: "GENERATE_FAILURE",

  REGENERATE_REQUEST: "REGENERATE_REQUEST",
  REGENERATE_SUCCESS: "REGENERATE_SUCCESS",
  REGENERATE_FAILURE: "REGENERATE_FAILURE",

  GET_CITATION_STYLE_REQUEST: "GET_CITATION_STYLE_REQUEST",
  GET_CITATION_STYLE_SUCCESS: "GET_CITATION_STYLE_SUCCESS",
  GET_CITATION_STYLE_FAILURE: "GET_CITATION_STYLE_FAILURE",
};